blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('bloggers/', views.BloggerListView.as_view(), name='bloggers'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
    path('blogs/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail' ),
    path('blogs/<int:pk>/create', views.CommentCreateView.as_view(), name='create'),
    path('blogs', views.BlogpostListView.as_view(), name='blogs'),
]

diyblog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.urls import reverse
from django.db import models

# Create your models here.
class Blogger(models.Model):
    """Model representing a blogger."""
    first_name = models.CharField(max_length=100, null=False, blank=False)
    last_name = models.CharField(max_length=100, null=False, blank=False)
    pseudonym = models.CharField(max_length=50, unique=True, null=True)
    bio = models.TextField(max_length=1000, null=False, blank=False, help_text="Some information about you would be great... ")

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse("blogger-detail", args=[str(self.id)])


    def __str__(self):
        return f'{self.first_name}, {self.last_name}'

class Blogpost(models.Model):
    """Model representing a blog post."""
    title = models.CharField(max_length=200, null=False, blank=False)
    #? Foreign key used because a blog post can only have one author(blogger), but authors can have multiple blog posts
    author = models.ForeignKey(Blogger, on_delete=models.CASCADE) # Foreign key is a 'one-to-many- field. Where is it declared, that is the 'one' side
    post_date = models.DateTimeField(auto_now_add= True) # Date when it was posted
    description = models.TextField(max_length=3000, help_text="Type something amazing...") # Blog content.
    tag = models.ManyToManyField('Tag', help_text='Select a genre for this blog post')

    class Meta:
        ordering = ['post_date']
        permissions =(("can_edit_blog_post", "Edit blog post"), )

    def __str__(self):
        return self.title

class Comment(models.Model):
    """Model representing a comment."""
    commenter = models.CharField(max_length=200) #! This needs to be a User object
    reaction = models.CharField(max_length=200, default='This is great!' ,null=False, blank=False)
    comment_date = models.DateField(auto_now_add=True, editable=False)
    post = models.ForeignKey(Blogpost, on_delete=models.CASCADE) #? When using PostgreSQL, a post_id column will be created by default.
                                                                 #? Make sure it is passed when saving the comment object in the DB
    class Meta:
        ordering = ['comment_date']

    def __str__(self):
        """String for the commenter and the comment date"""
        return f'{self.commenter} ({self.comment_date})'

    # def get_absolute_url(self): # new
    #     return reverse('blogs')

class Tag(models.Model):
    """Model representing a blog post genre."""
    name = models.CharField(max_length=200, help_text='Enter the category of your blog post (e.g Business, self help...)')

    def __str__(self):
        """String for representing model tag/genre"""
        return self.name

blog/forms.py
from django_registration.forms import RegistrationForm
from .models import Comment
from django import forms

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Blogger, Blogpost, Comment
from django.views import generic
from django.views.generic.edit import  CreateView, DeleteView, ModelFormMixin
from django.urls import reverse_lazy, reverse

# Create your views here.
def index(request):
    bloggers = Blogger.objects.all()
    context = {
        "bloggers":bloggers,
    }
    return render(request, 'index.html', context)


class BloggerListView(generic.ListView):
    model = Blogger
    paginate_by = 10


class BloggerDetailView(generic.DetailView):
    model = Blogger


class BlogpostListView(generic.ListView):
    model = Blogpost
    paginate_by = 10


class BlogDetailView(generic.DetailView):
    model = Blogpost


class CommentCreateView(generic.CreateView):
    model = Comment
    fields = ['reaction']
    success_url = reverse_lazy("blog-detail")

    def get_context_data(self, **kwargs):
        context = super(CommentCreateView, self).get_context_data(**kwargs)
        context["blogpost"] = get_object_or_404(Blogpost, pk = self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """ Add Author and associated blog before saving"""
        # Add logged in user as the commenter
        form.instance.commenter = self.request.user
        # Associate the comment with the blogpost id
        form.instance.blogpost = get_object_or_404(Blogpost.post_set.id, pk = self.kwargs['pk'])
        # print(form.instance.blogpost.id)
        # Call super class form validation behavior
        return super(CommentCreateView, self).form_valid(form)


    def get_success_url(self, **kwargs):
        context = super(CommentCreateView, self).get_context_data(**kwargs)
        return reverse(context(pk=self.kwargs['pk']))

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block title %}<title>DIY blog</title>{% endblock title %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{%url 'blogs' %}">All blogs</a></li>
                        <li><a href="{% url 'bloggers' %}">All bloggers</a></li>
                    </ul>
                {%endblock sidebar %}

                <ul class="sidebar-nav">
                    <!-- More to be added here including permission enforced links -->
                    {% if user.is_authenticated%}
                        User: {{user.get_username}}
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else%}
                        <a href="{% url 'login' %}?next={{request.path}}">Login</a>
                    {% endif %}
                </ul>
            </div>
<!-- Separation between the nav bar code and the main page code -->
            <div class="col-sm-10">
                {% block content %}
                {% endblock content %}
                <!-- Some pagination in some pages may come in handy in this place -->
            </div>
        </div>

    </div>
</body>
</html>

blog/templates/blog/blog_list.html
{% extends 'base_generic.html' %}

{% block content %}
{% endblock content %}

blog/templates/blog/blogger_detail.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>Blogger: {{blogger}}</h1>
<h5>{{blogger.pseudonym}}</h5>
<hr>
<h4>Bio</h4>
<p>{{blogger.bio}}</p>
<hr>
<p>Blog Posts</p>
<dl>
{% for blogs in blogger.blogpost_set.all %}
<li><a href="{% url 'blog-detail' blogs.pk %}">{{blogs}}</a></li>
{% endfor %}

</dl>


{% endblock content %}

blog/templates/blog/blogger_list.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>All Bloggers</h1>
{% if blogger_list %}
    {% for blogger in blogger_list %}
        <li><a href="{{blogger.get_absolute_url}}">{{blogger.pseudonym}}</a></li>
    {% endfor %}
{% endif %}

{% endblock content %}

blog/templates/blog/blogpost_detail.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>{{blogpost.title}}</h1>
<h6>{{blogpost.post_date}}</h6>
<h6><a href="{% url 'blogger-detail' blogpost.author.pk %}">{{blogpost.author.pseudonym}}</a></h6>
<hr>
<p>{{blogpost.description}}</p>

<div style="margin-top: 20px; margin-left: 20px;">
    <h4>Comments</h4>
    <hr>
    {% for comment in blogpost.comment_set.all %}
        <p>{{comment.commenter}} ({{comment.comment_date}}) - {{comment.reaction}}</p>
        <hr>
    {% endfor %}

</div>
{% if user.is_authenticated %}
<a href="{% url 'create' blogpost.id %}">Add a comment</a>
{% else %}
<p>a href="{% url 'login' %}">login</a> to make a comment </p>
{% endif %}
{% endblock content %}

blog/templates/blog/blogpost_list.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>All Blogs</h1>
{{blogpost.title}}
{% if blogpost_list %}
{% for blog in blogpost_list     %}
<li><a href="{% url 'blog-detail' blog.pk %}">{{blog.title}}</a> ({{blog.post_date}}) - <a href="{% url 'blogger-detail' blog.author.pk %}">{{blog.author.pseudonym}}</a></li>
{% endfor %}
{% endif %}

{% endblock content %}

blog/templates/blog/comment_form.html
{% extends 'base_generic.html' %}
{% block content %}
<p>Post your comment for: {{blogpost.title}} </p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

blog/templates/index.html
{% extends 'base_generic.html' %}
{% block content %}

<h1>All bloggers</h1>
<ul>
    {% for blogger in bloggers%}
    <li><a href="{{blogger.get_absolute_url}}">{{blogger.first_name}}</a> {{blogger.last_name}} A.K.A {{blogger.pseudonym}}</li>
    {% endfor %}
</ul>
{% endblock content %}